@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDU4MzkwMzh9._AG9T5F76x7Vf8POVrEtCXDKCsfOhsuqcGDuf5sTbhI

###get all users
GET http://localhost:3000/users

###show user
GET http://localhost:3000/users/3
Authorization: Bearer {{ jwt }}

###create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "testing@test.com",
  "username": "test!",
  "first_name": "testy",
  "last_name": "test",
  "description": "this is a test",
  "password": "password",
  "password_confirmation": "password"
}

###login
post http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "password"
}




###index posts
get http://localhost:3000/posts

###show post
get http://localhost:3000/posts/1
Authorization: Bearer {{ jwt }}

###create post
post http://localhost:3000/posts
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "title": "Test Post 2",
  "audio_url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
  "description": "This is a test"
}